"""Load Olist raw CSVs into Lakebase Postgres OLTP schema — 11-table star
schema (facts: orders, order_items, reviews; dimensions: customers, products,
dim_category, sellers, geolocation, dim_date, dim_marketing_channel; bridge:
order_channel).

Prereqs:
    1. data/sql/oltp_schema.sql has been applied to the target Postgres
    2. LAKEBASE_URL is exported, e.g.
         postgresql://user@host:5432/dbname?sslmode=require
       Leave the password out of the URL — you'll be prompted for it
       interactively (not echoed, not stored in shell history). If
       LAKEBASE_URL does already include a password (e.g. in CI, piped from
       a secrets manager), that password is used as-is and you won't be
       prompted.
    3. Olist CSVs are in data/raw/ with their original filenames (see
       SOURCES below for the full list, including
       product_category_name_translation.csv)
    4. The two synthetic/derived dimensions have already been generated:
         python data/pipelines/build_dim_date.py
         python data/pipelines/build_dim_marketing_channel.py
       (both write into data/processed/ — this script reads them from there,
       it does not regenerate them, so re-running this loader alone won't
       go stale on those two as long as you re-run the generators when the
       order data changes)

Side effects:
    - Writes cleaned, schema-aligned CSVs to data/processed/ for the OLAP path.
    - TRUNCATEs and reloads all OLTP tables (idempotent).

Load order matters: TRUNCATE ... CASCADE on a dimension wipes any fact that
references it, so dimensions load before the facts that depend on them
(dim_date and dim_marketing_channel before orders; dim_category before
products; customers/sellers before orders/order_items). Don't reorder the
`tables` list in main() without checking the FK graph in oltp_schema.sql.

Usage:
    pip install -r data/pipelines/requirements.txt
    LAKEBASE_URL=... python data/pipelines/load_oltp.py
"""
from __future__ import annotations

import getpass
import os
from io import StringIO
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pandas as pd
import psycopg2

DATA = Path(__file__).resolve().parents[1]      # …/data
RAW = DATA / "raw"
PROCESSED = DATA / "processed"
PROCESSED.mkdir(exist_ok=True)

# Olist's original filenames; rename here if you've shortened them.
SOURCES = {
    "customers":            "olist_customers_dataset.csv",
    "orders":                "olist_orders_dataset.csv",
    "order_items":           "olist_order_items_dataset.csv",
    "products":               "olist_products_dataset.csv",
    "payments":               "olist_order_payments_dataset.csv",
    "sellers":                "olist_sellers_dataset.csv",
    "geolocation":            "olist_geolocation_dataset.csv",
    "reviews":                "olist_order_reviews_dataset.csv",
    "category_translation":   "product_category_name_translation.csv",
}

# Pre-generated by build_dim_date.py / build_dim_marketing_channel.py — not
# cleaned here, just loaded as-is.
GENERATED = {
    "dim_date":              "dim_date.csv",
    "dim_marketing_channel": "dim_marketing_channel.csv",
    "order_channel":         "order_channel_bridge.csv",
}


def clean_customers() -> pd.DataFrame:
    df = pd.read_csv(RAW / SOURCES["customers"])
    df = df[["customer_id", "customer_unique_id", "customer_city", "customer_state"]]
    df = df.rename(columns={"customer_city": "city", "customer_state": "state"})
    return df.dropna(subset=["customer_id", "customer_unique_id"])


def clean_sellers() -> pd.DataFrame:
    df = pd.read_csv(RAW / SOURCES["sellers"])
    df = df[["seller_id", "seller_city", "seller_state"]]
    df = df.rename(columns={"seller_city": "city", "seller_state": "state"})
    return df.dropna(subset=["seller_id"]).drop_duplicates(subset=["seller_id"])


def clean_geolocation() -> pd.DataFrame:
    # Olist's raw geolocation file is zip-prefix level with many duplicate/
    # near-duplicate rows (multiple lat/lng samples per prefix). Collapse to
    # one row per zip_code_prefix (average coordinates) so it's usable as a
    # clean dimension rather than a multi-million-row noise table.
    df = pd.read_csv(RAW / SOURCES["geolocation"])
    df = df.rename(columns={
        "geolocation_zip_code_prefix": "zip_code_prefix",
        "geolocation_city":            "city",
        "geolocation_state":           "state",
        "geolocation_lat":             "lat",
        "geolocation_lng":             "lng",
    })
    df["zip_code_prefix"] = df["zip_code_prefix"].astype(str)
    agg = (
        df.groupby("zip_code_prefix")
        .agg(city=("city", "first"), state=("state", "first"),
             lat=("lat", "mean"), lng=("lng", "mean"))
        .reset_index()
    )
    return agg.dropna(subset=["zip_code_prefix"])


def clean_dim_category() -> pd.DataFrame:
    products_raw = pd.read_csv(RAW / SOURCES["products"], usecols=["product_category_name"])
    translation = pd.read_csv(RAW / SOURCES["category_translation"])

    names = products_raw["product_category_name"].dropna().unique()
    dim = pd.DataFrame({"category_name": sorted(names)})
    dim = dim.merge(translation, how="left",
                     left_on="category_name", right_on="product_category_name")
    dim = dim.rename(columns={"product_category_name_english": "category_name_english"})
    dim = dim[["category_name", "category_name_english"]]
    # Explicit, stable id — see the comment in oltp_schema.sql on why this
    # isn't a Postgres SERIAL: products.category_id needs the mapping before
    # the COPY happens, not after.
    dim.insert(0, "category_id", range(1, len(dim) + 1))
    return dim


def clean_products(dim_category: pd.DataFrame) -> pd.DataFrame:
    df = pd.read_csv(RAW / SOURCES["products"])
    df = df[[
        "product_id",
        "product_category_name",
        "product_weight_g",
        "product_length_cm",
        "product_height_cm",
        "product_width_cm",
    ]]
    df = df.merge(
        dim_category[["category_id", "category_name"]],
        how="left", left_on="product_category_name", right_on="category_name",
    )
    df = df.rename(columns={
        "product_weight_g":  "product_weight",
        "product_length_cm": "product_length",
        "product_height_cm": "product_height",
        "product_width_cm":  "product_width",
    })
    df = df[["product_id", "category_id", "product_weight",
             "product_length", "product_height", "product_width"]]
    # The merge produces NaN for any product whose category_name didn't
    # match (e.g. a blank category in the source row), which silently
    # upcasts category_id from int to float — Postgres then rejects "63.0"
    # for an INTEGER column. Int64 (capital-I, pandas' nullable integer
    # type) keeps real values as clean integers and turns missing ones into
    # an empty CSV field, which COPY reads as a proper NULL.
    df["category_id"] = df["category_id"].astype("Int64")
    return df.dropna(subset=["product_id"])


def clean_orders() -> pd.DataFrame:
    df = pd.read_csv(
        RAW / SOURCES["orders"],
        parse_dates=["order_purchase_timestamp", "order_delivered_customer_date"],
    )
    df = df[[
        "order_id",
        "customer_id",
        "order_status",
        "order_purchase_timestamp",
        "order_delivered_customer_date",
    ]]
    df = df.rename(columns={"order_delivered_customer_date": "order_delivered_timestamp"})
    df = df.dropna(subset=["order_id", "customer_id", "order_status", "order_purchase_timestamp"])
    # order_date_key joins to dim_date — same YYYYMMDD-integer convention
    # build_dim_date.py uses.
    df["order_date_key"] = df["order_purchase_timestamp"].dt.strftime("%Y%m%d").astype(int)
    return df


def clean_order_items(valid_orders: set[str], valid_products: set[str],
                       valid_sellers: set[str]) -> pd.DataFrame:
    df = pd.read_csv(RAW / SOURCES["order_items"])
    df = df[["order_id", "product_id", "seller_id", "price", "freight_value"]]
    df = df.dropna(subset=["order_id", "product_id", "price", "freight_value"])
    df = df[df["order_id"].isin(valid_orders) & df["product_id"].isin(valid_products)]
    # seller_id is nullable in the schema, but if present it must be valid —
    # blank it out rather than drop the row over a bad/missing seller ref.
    df.loc[~df["seller_id"].isin(valid_sellers), "seller_id"] = None
    return df


def clean_payments(valid_orders: set[str]) -> pd.DataFrame:
    df = pd.read_csv(RAW / SOURCES["payments"])
    df = df[["order_id", "payment_type", "payment_value", "payment_installments"]]
    df = df.dropna(subset=["order_id", "payment_type", "payment_value", "payment_installments"])
    df["payment_installments"] = df["payment_installments"].astype(int)
    return df[df["order_id"].isin(valid_orders)]


def clean_reviews(valid_orders: set[str]) -> pd.DataFrame:
    df = pd.read_csv(RAW / SOURCES["reviews"], parse_dates=["review_creation_date"])
    df = df[[
        "review_id", "order_id", "review_score",
        "review_comment_title", "review_comment_message", "review_creation_date",
    ]]
    df = df.dropna(subset=["review_id", "order_id", "review_score"])
    df = df.drop_duplicates(subset=["review_id"])
    return df[df["order_id"].isin(valid_orders)]


def load_generated(name: str) -> pd.DataFrame:
    path = PROCESSED / GENERATED[name]
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found — run build_dim_date.py and "
            "build_dim_marketing_channel.py before load_oltp.py."
        )
    return pd.read_csv(path)


def resolve_db_url(raw_url: str) -> str:
    """Fill in the Postgres password interactively if LAKEBASE_URL doesn't
    already carry one, so it never has to sit in an env var or shell
    history for local/interactive use. If a password is already present
    (CI, secrets manager), it's left untouched and nothing is prompted."""
    parts = urlsplit(raw_url)
    if parts.password:
        return raw_url

    user = parts.username or "postgres"
    password = getpass.getpass(f"Postgres password for {user}@{parts.hostname}: ")

    userinfo = f"{user}:{password}"
    host = parts.hostname or ""
    if parts.port:
        host = f"{host}:{parts.port}"
    netloc = f"{userinfo}@{host}"

    return urlunsplit((parts.scheme, netloc, parts.path, parts.query, parts.fragment))


def copy_to_table(conn, table: str, df: pd.DataFrame) -> None:
    buf = StringIO()
    df.to_csv(buf, index=False, header=False)
    buf.seek(0)
    cols = ",".join(df.columns)
    with conn.cursor() as cur:
        cur.execute(f"TRUNCATE TABLE {table} CASCADE")
        cur.copy_expert(f"COPY {table} ({cols}) FROM STDIN WITH (FORMAT csv)", buf)


def main() -> None:
    db_url = resolve_db_url(os.environ["LAKEBASE_URL"])

    # Dimensions with no FK dependencies first.
    dim_date = load_generated("dim_date")
    dim_marketing_channel = load_generated("dim_marketing_channel")
    dim_category = clean_dim_category()
    customers = clean_customers()
    sellers = clean_sellers()
    geolocation = clean_geolocation()

    # Then things that reference those dimensions.
    products = clean_products(dim_category)
    orders = clean_orders()
    order_items = clean_order_items(set(orders.order_id), set(products.product_id), set(sellers.seller_id))
    payments = clean_payments(set(orders.order_id))
    reviews = clean_reviews(set(orders.order_id))
    order_channel = load_generated("order_channel")
    order_channel = order_channel[order_channel["order_id"].isin(set(orders.order_id))]

    # Load order must match the FK graph in oltp_schema.sql — TRUNCATE
    # ... CASCADE on a dimension wipes any fact loaded before it that
    # references it. Dimensions first, then facts, then the bridge.
    tables = [
        ("dim_date",              dim_date),
        ("dim_marketing_channel", dim_marketing_channel),
        ("dim_category",          dim_category),
        ("customers",             customers),
        ("sellers",               sellers),
        ("geolocation",           geolocation),
        ("products",              products),
        ("orders",                orders),
        ("order_items",           order_items),
        ("payments",              payments),
        ("reviews",               reviews),
        ("order_channel",         order_channel),
    ]

    for name, df in tables:
        out = PROCESSED / f"{name}.csv"
        df.to_csv(out, index=False)
        print(f"  cleaned {name:<22} {len(df):>9,} rows  →  {out.relative_to(DATA.parent)}")

    print(f"\nConnecting to Lakebase…")
    with psycopg2.connect(db_url) as conn:
        for name, df in tables:
            print(f"  loading {name}…")
            copy_to_table(conn, name, df)
        conn.commit()
    print("OLTP load complete.")


if __name__ == "__main__":
    main()
