spring.application.name=noticeboard-backend
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/noticeboard}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.recipient=${NOTIFICATION_RECIPIENT_EMAIL:hr@example.com}
